[package]
name = "pmacct-gauze-bindings"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[build-dependencies]
bindgen = { git = "https://github.com/mxyns/rust-bindgen", branch = "extended-callbacks", version = "0.68.1" }
proc-macro2 = "1.0.67"
quote = "1.0.33"