use std::ffi::c_int;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};

use ipnet::{IpNet, Ipv4Net, Ipv6Net, PrefixLenError};
use libc::{AF_INET, AF_INET6};

use crate::{AFI_IP, AFI_IP6, bgp_afi2family, host_addr, host_addr__bindgen_ty_1, in6_addr, in6_addr__bindgen_ty_1, in_addr, prefix, prefix__bindgen_ty_1};

impl From<&Ipv4Addr> for in_addr {
    fn from(value: &Ipv4Addr) -> Self {
        in_addr {
            s_addr: value.to_bits().to_be(),
        }
    }
}

impl From<&in_addr> for Ipv4Addr {
    fn from(value: &in_addr) -> Self {
        (*value).into()
    }
}

impl From<in_addr> for Ipv4Addr {
    fn from(value: in_addr) -> Self {
        Ipv4Addr::from_bits(u32::from_be(value.s_addr))
    }
}

impl From<&Ipv6Addr> for in6_addr {
    fn from(value: &Ipv6Addr) -> Self {
        in6_addr {
            __in6_u: in6_addr__bindgen_ty_1 {
                __u6_addr8: value.octets(),
            },
        }
    }
}

impl From<&in6_addr> for Ipv6Addr {
    fn from(value: &in6_addr) -> Self {
        unsafe { Ipv6Addr::from(value.__in6_u.__u6_addr8) }
    }
}

impl From<&Ipv4Net> for prefix {
    fn from(value: &Ipv4Net) -> Self {
        prefix {
            family: unsafe { bgp_afi2family(AFI_IP as c_int) } as u8,
            prefixlen: value.prefix_len(),
            __bindgen_padding_0: 0,
            u: prefix__bindgen_ty_1 {
                prefix4: (&value.network()).into(),
            },
        }
    }
}

impl From<&Ipv6Net> for prefix {
    fn from(value: &Ipv6Net) -> Self {
        prefix {
            family: unsafe { bgp_afi2family(AFI_IP6 as c_int) } as u8,
            prefixlen: value.prefix_len(),
            __bindgen_padding_0: 0,
            u: prefix__bindgen_ty_1 {
                prefix6: (&value.network()).into(),
            },
        }
    }
}

impl From<&Ipv6Addr> for host_addr {
    fn from(value: &Ipv6Addr) -> Self {
        host_addr {
            family: unsafe { bgp_afi2family(AFI_IP6 as c_int) } as u8,
            address: host_addr__bindgen_ty_1 { ipv6: value.into() },
        }
    }
}

impl From<&Ipv4Addr> for host_addr {
    fn from(value: &Ipv4Addr) -> Self {
        host_addr {
            family: unsafe { bgp_afi2family(AFI_IP as c_int) } as u8,
            address: host_addr__bindgen_ty_1 { ipv4: value.into() },
        }
    }
}

impl From<&IpAddr> for host_addr {
    fn from(value: &IpAddr) -> Self {
        match value {
            IpAddr::V4(v4) => v4.into(),
            IpAddr::V6(v6) => v6.into(),
        }
    }
}

#[derive(Debug, Ord, PartialOrd, Eq, PartialEq, Copy, Clone, Hash)]
pub struct AddrFamilyError;

impl TryFrom<&host_addr> for IpAddr {
    /// BAD FAMILY VALUE
    type Error = AddrFamilyError;

    fn try_from(value: &host_addr) -> Result<Self, Self::Error> {
        match value.family as i32 {
            AF_INET => unsafe {
                Ok(IpAddr::V4(Ipv4Addr::from(value.address.ipv4)))
            }
            AF_INET6 => unsafe {
                Ok(IpAddr::V6(Ipv6Addr::from(&value.address.ipv6)))
            }
            _ => {
                Err(AddrFamilyError)
            }
        }
    }
}
#[allow(clippy::derivable_impls)] // this struct definition is autogenerated
impl Default for in_addr {
    fn default() -> Self {
        in_addr { s_addr: 0 }
    }
}

impl Default for in6_addr {
    fn default() -> Self {
        in6_addr {
            __in6_u: in6_addr__bindgen_ty_1 {
                __u6_addr8: [0u8; 16],
            },
        }
    }
}

impl Default for host_addr {
    fn default() -> Self {
        host_addr {
            family: 0,
            // use the ipv6 union variant because, as the largest, it defines the union size
            address: host_addr__bindgen_ty_1 {
                ipv6: in6_addr::default(),
            },
        }
    }
}

impl host_addr {
    pub fn default_ipv4() -> Self {
        host_addr {
            family: unsafe { bgp_afi2family(AFI_IP as c_int) } as u8,
            address: host_addr__bindgen_ty_1 {
                ipv4: in_addr::default(),
            },
        }
    }

    pub fn default_ipv6() -> Self {
        host_addr {
            family: unsafe { bgp_afi2family(AFI_IP6 as c_int) } as u8,
            address: host_addr__bindgen_ty_1 {
                ipv6: in6_addr::default(),
            },
        }
    }
}

#[derive(Debug, Ord, PartialOrd, Eq, PartialEq, Copy, Clone, Hash)]
pub enum PrefixError {
    PrefixLenError,
    AddrFamilyError,
}

impl From<PrefixLenError> for PrefixError {
    fn from(_value: PrefixLenError) -> Self {
        PrefixError::PrefixLenError
    }
}

impl TryFrom<&prefix> for IpNet {
    type Error = PrefixError;

    fn try_from(value: &prefix) -> Result<Self, Self::Error> {
        match value.family as i32 {
            AF_INET => unsafe {
                Ok(IpNet::V4(Ipv4Net::new(Ipv4Addr::from(&value.u.prefix4), value.prefixlen)?))
            }
            AF_INET6 => unsafe {
                Ok(IpNet::V6(Ipv6Net::new(Ipv6Addr::from(&value.u.prefix6), value.prefixlen)?))
            }
            _ => {
                Err(PrefixError::AddrFamilyError)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::net::Ipv4Addr;

    use crate::in_addr;

    #[test]
    fn in_addr_from_ipv4_addr() {
        let ip = Ipv4Addr::new(254, 1, 128, 127);
        let _other = in_addr::from(&ip);
    }
}
