[package]
name = "pmacct-gauze-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-c = { version = "0.9.24" }
libc = "0.2.148"
netgauze-parse-utils = "0.1.0"
netgauze-bmp-pkt = "0.1.0"
nom = "7.1.3"
pmacct-gauze-bindings = { path = "../pmacct-gauze-bindings" }

[features]
capi = []