#![feature(let_chains)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(improper_ctypes)]
#![allow(dead_code)]

pub use bindings::*;

pub mod convert;
pub mod print;

/// This module is generated by `build.rs` in the build directory
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

