#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[cfg(feature = "capi")]
pub mod c_api;

/// This module is generated by `build.rs`, either in the build directory,
/// or in the `src` directory with feature `source-bindings` for IDEs to understand the symbols

#[cfg(feature = "source-bindings")]
pub mod bindings;

#[cfg(not(feature = "source-bindings"))]
pub mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(test)]
mod tests {

    #[test]
    fn test() {}
}
